### ISSUE TITLE
Logging out doesn't redirect properly.

### ISSUE THREAD

**Issue by chriseaton** [fragmenta/fragmenta-cms#20]
Setup brand new fragmenta site. Log in. Then click the logout link. Instead of redirecting to "/" it shows a 404. Examining the logs it shows a very strange set of events:

````
2016/03/23 21:43:26 #info Started GET /users/logout for {my ip}
2016/03/23 21:43:26 #info Started POST /users/logout for {my ip}
2016/03/23 21:43:26 #info Handling with route [POST] /users/logout
2016/03/23 21:43:26 #info Handling with route [GET] /{path:[a-z0-9]+}
2016/03/23 21:43:26 #info Redirecting (302) to path:/
2016/03/23 21:43:26 #info Finished POST /users/logout for {my ip} status 200 in 1.35173ms
2016/03/23 21:43:26 #error Status 404 at src/pages/actions/show.go:44 : Error:404
2016/03/23 21:43:26 #info Started GET / for {my ip}
2016/03/23 21:43:26 #info Handling with route [GET] /
2016/03/23 21:43:26 #info Finished GET / for {my ip} status 200 in 16.520678ms
````

Why is there a log for a POST? I tried digging around but I think somewhere the request isn't following through all the way (maybe?) Tried on Chrome and Firefox, same result.

**Comment by chriseaton** [comment]
Figured it out. There's a bug in the cms's src/app/routes.go
````
r.Add("/users/logout", useractions.HandleLogout).Post()
````
should be (or include)
````
r.Add("/users/logout", useractions.HandleLogout)
````

**Comment by kennygrant** [comment]
The logout action is intended to be POST (see notes on pull request). I'll see if I can work out what is going on here though, it looks like the wrong route might be handling the logout for some reason.

**Comment by kennygrant** [comment]
The logout action is inherently not idempotent, it changes user state. You may find this discussion interesting on this:

http://stackoverflow.com/questions/3521290/logout-get-or-post#14587231

**Comment by chriseaton** [comment]
I guess that depends on whether you consider the user state a true RESTful resource or not. In REST resources are generally as presented to the user via URI, not something representing the state held on the server. See VinayC, Joel Etherton, & Darrel Miller's answers on the page you linked.

**Comment by kennygrant** [comment]
Most sites have moved to post for a logout link, for good practical reasons - see github, stackoverflow etc. The top response on that page linked recommends it for this reason. Clients may fetch get links expecting them to have no effect (perfectly reasonably), and it's not OK for them to have an effect on the user's state IMO. Web crawlers, prefetchers etc all depend on that behaviour and it also lets you check for XSRF on only post links. 

While REST is an interesting guideline it is not possible to fully implement due to patchy browser support, and can lead to bikeshedding over URLs which is not useful or productive (/users/logout vs /sessions DELETE etc etc). 

Re the requirement for javascript, another approach would be to use an inline hidden form for the logout link (see the github logout link), but I think it's neater to require js as most sites have quite a few actions (like upvoting, or subscribe to something for example) which are better described as links with a method=post decorator, and most users don't mind having js turned on for a site they're actively using (passive readers this doesn't affect).

**Comment by chriseaton** [comment]
My understanding is that prefetching only occurs when links are tagged as such or linked via script or link tag or if you have some kind of weird accelerator add-on to your browser. I've never had a server get "accidental" logouts when providing logout via GET as there's no reason to ever link to the logout URL through a link or script tag.

Saying that another site could provide a hidden GET logout request isn't valid, as such a request wouldn't pass the authentication cookie (x-domain protections), and another site could just as easily do a POST or any other type of method request via Javascript, so this is a non-sequitor. 

Web crawlers aren't a concern unless you're providing some mechanism for them to log in.

If it is truly a worry, most browsers include a header tag for pre-fetches, such as "X-moz: prefetch" for Firefox, and "X-Purpose: preview" for Chrome and Safari, which could be checked server-side.

I understand there's a stack overflow post where the top answer expresses use of POST, but that doesn't make it an informed, or even practical answer. But anyways, it's obvious I'm not going to convince you or vice versa so we'll just have to agree to disagree.
