### ISSUE TITLE
Don't tell after a failed login if the user is not present or if it's a bad password

### ISSUE THREAD

**Issue by Swatto** [fragmenta/fragmenta-cms#5]
From my point of view, we shouldn't tell to the user if it's an error from the login or from the password.
As a security issue, this open a possibility to brute-force the login handler to find a registered user then his password.

We should remove the two different messages and argument given by the redirect handler (`?error=failed_email`).

**Comment by kennygrant** [comment]
There are different schools of thought on this. One is as you state - that you could be the victim of an enumeration attack if you give the user information about what failed. The other is that this doesn't really matter because there are other methods for determining a valid registered user - for example attempting to create a user with a given mail and failing will tell you if one exists for that email. That is unavoidable, so all websites are vulnerable to user enumeration via that method if they allow account signup with email. User emails will often not be secret anyway (for example a company site with emails published online for contact info, or a dev email published in git commits), which again is another channel to guess email accounts used, so I think it's misleading to think of them as secret, they are usually easily discoverable. 

The problem with this information hiding approach on the login page is that you're not giving the user information on what failed, so you're making life worse for your real users (who get emails and passwords wrong surprisingly often, and may not know which email they used), while not really protecting against a user enumeration attack. So this is why the page tells you what went wrong. 

I think I prefer the idea of rate limiting by IP to stop malicious enumeration or login attempts (and also protect against a simplistic DOS with a flood of requests), rather than hiding information from the user. So I'd rather explore adding a filter to do that (there is some middleware available for this that I'm going to look into).

**Comment by Swatto** [comment]
Two approaches as your said, with different visions and I respect you choice.

As you prefer to stay in the current behavior, I like the idea to add a filter (as a middleware) for that. Don't you think that the max amount of try per IP should be configurable ? Also the timeout added to the next try allowed could be in the configuration.

**Comment by kennygrant** [comment]
Thanks for the ideas, I've opened another issue about that for discussion.
